"""add attachment_ids to agent_messages

Revision ID: 78515111bbfd
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 15:17:52.348496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78515111bbfd"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first (existing rows will have NULL)
    op.add_column(
        "agent_messages", sa.Column("attachment_ids", sa.JSON(), nullable=True)
    )
    # Update existing rows to have empty arrays
    op.execute(
        "UPDATE agent_messages SET attachment_ids = '[]'::json WHERE attachment_ids IS NULL"
    )
    # Now make it NOT NULL
    op.alter_column("agent_messages", "attachment_ids", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_messages", "attachment_ids")
    # ### end Alembic commands ###
