"""add_multi_chat_threads

Revision ID: 8a77b1a31128
Revises: b8c9d0e1f2a3
Create Date: 2026-06-05 14:01:43.737161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a77b1a31128"
down_revision: Union[str, Sequence[str], None] = "b8c9d0e1f2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server default first to support existing rows safely
    op.add_column(
        "agent_threads",
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            server_default="New Conversation",
        ),
    )
    # Backfill existing threads with human-friendly names based on their agent type
    op.execute(
        "UPDATE agent_threads SET title = 'Co-Founder Chat' WHERE agent_type = 'cofounder'"
    )
    op.execute(
        "UPDATE agent_threads SET title = 'Finance Chat' WHERE agent_type = 'finance'"
    )
    op.execute(
        "UPDATE agent_threads SET title = 'Marketing Chat' WHERE agent_type = 'marketing'"
    )
    op.execute(
        "UPDATE agent_threads SET title = 'Product Chat' WHERE agent_type = 'product'"
    )
    # Remove the server default so future inserts rely on SQLAlchemy model default or explicit title
    op.alter_column("agent_threads", "title", server_default=None)

    op.drop_constraint("uq_agent_thread_project_agent", "agent_threads", type_="unique")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_agent_thread_project_agent"),
        "agent_threads",
        ["project_id", "agent_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("agent_threads", "title")
    # ### end Alembic commands ###
